// TAIGA

import { MaskitoModule } from '@maskito/angular';
import {
	TuiActiveZoneModule,
	TuiAlertHostModule,
	TuiAutoFocusModule,
	TuiAutofilledModule,
	TuiCheckedModule,
	TuiClickOutsideModule,
	TuiControlModule,
	TuiCopyProcessorModule,
	TuiDialogHostModule,
	TuiDragModule,
	TuiDropdownHostModule,
	TuiDroppableModule,
	TuiElementModule,
	TuiFilterPipeModule,
	TuiFocusTrapModule,
	TuiFocusVisibleModule,
	TuiFocusableModule,
	TuiFocusedModule,
	TuiForAsyncModule,
	TuiForModule,
	TuiHighDpiModule,
	TuiHoveredModule,
	TuiIsPresentPipeModule,
	TuiItemModule,
	TuiKeysPipeModule,
	TuiLetModule,
	TuiMapperPipeModule,
	TuiMediaModule,
	TuiObscuredModule,
	TuiOverscrollModule,
	TuiPanModule,
	TuiPlatformModule,
	TuiPortalModule,
	TuiPressedModule,
	TuiPreventDefaultModule,
	TuiRepeatTimesModule,
	TuiReplacePipeModule,
	TuiResizeModule,
	TuiResizerModule,
	TuiScrollControlsModule,
	TuiSwipeModule,
	TuiValidatorModule,
	TuiValueChangesModule,
	TuiZoomModule
} from '@taiga-ui/cdk';


import {
	TuiAlertModule,
	TuiButtonModule,
	TuiCalendarModule,
	TuiCalendarSheetPipeModule,
	TuiDataListModule,
	TuiDialogModule,
	TuiDropdownModule,
	TuiErrorModule,
	TuiExpandModule,
	TuiFlagPipeModule,
	TuiFormatDatePipeModule,
	TuiFormatNumberPipeModule,
	TuiFormatPhonePipeModule,
	TuiGroupModule,
	TuiHintModule,
	TuiHintsHostModule,
	TuiHostedDropdownModule,
	TuiLabelModule,
	TuiLinkModule,
	TuiLoaderModule,
	TuiMaskAccessorModule,
	TuiModeModule,
	TuiMonthPipeModule,
	TuiNotificationModule,
	TuiNumberFormatModule,
	TuiPrimitiveCalendarModule,
	TuiPrimitiveCheckboxModule,
	TuiPrimitiveSpinButtonModule,
	TuiPrimitiveTextfieldModule,
	TuiPrimitiveYearMonthPaginationModule,
	TuiPrimitiveYearPickerModule,
	TuiRootModule,
	TuiScrollIntoViewModule,
	TuiScrollbarModule,
	TuiSvgDefsHostModule,
	TuiSvgModule,
	TuiTextfieldControllerModule,
	TuiThemeNightModule,
	TuiTooltipModule,
	TuiWrapperModule
} from '@taiga-ui/core';
import {
	TextMaskModule,
	TuiAccordionModule,
	TuiActionModule,
	TuiArrowModule,
	TuiAvatarModule,
	TuiBadgeModule,
	TuiBadgedContentModule,
	TuiBreadcrumbsModule,
	TuiCalendarMonthModule,
	TuiCalendarRangeModule,
	TuiCarouselModule,
	TuiCheckboxBlockModule,
	TuiCheckboxLabeledModule,
	TuiCheckboxModule,
	TuiComboBoxModule,
	TuiDataListDropdownManagerModule,
	TuiDataListWrapperModule,
	TuiElasticContainerModule,
	TuiExtractCountryCodeModule,
	TuiFieldErrorPipeModule,
	TuiFilesModule,
	TuiFilterByInputPipeModule,
	TuiFilterModule,
	TuiHighlightModule,
	TuiInputCopyModule,
	TuiInputCountModule,
	TuiInputDateModule,
	TuiInputDateMultiModule,
	TuiInputDateRangeModule,
	TuiInputDateTimeModule,
	TuiInputFilesModule,
	TuiInputInlineModule,
	TuiInputModule,
	TuiInputMonthModule,
	TuiInputMonthRangeModule,
	TuiInputNumberModule,
	TuiInputPasswordModule,
	TuiInputPhoneInternationalModule,
	TuiInputPhoneModule,
	TuiInputRangeModule,
	TuiInputSliderModule,
	TuiInputTagModule,
	TuiInputTimeModule,
	TuiInputYearModule,
	TuiIslandModule,
	TuiIsoToCountryCodeModule,
	TuiItemsWithMoreModule,
	TuiLazyLoadingModule,
	TuiLineClampModule,
	TuiMarkerIconModule,
	TuiMultiSelectModule,
	TuiMultiSelectOptionModule,
	TuiPaginationModule,
	TuiPdfViewerModule,
	TuiPresentModule,
	TuiPrimitiveCalendarRangeModule,
	TuiProgressModule,
	TuiProjectClassModule,
	TuiPromptModule,
	TuiPushModule,
	TuiRadioBlockModule,
	TuiRadioGroupModule,
	TuiRadioLabeledModule,
	TuiRadioListModule,
	TuiRadioModule,
	TuiRangeModule,
	TuiRatingModule,
	TuiRoutableDialogModule,
	TuiSelectModule,
	TuiSelectOptionModule,
	TuiSliderModule,
	TuiSortCountriesPipeModule,
	TuiStepperModule,
	TuiStringifyContentPipeModule,
	TuiStringifyPipeModule,
	TuiTabsModule,
	TuiTagModule,
	TuiTextAreaModule,
	TuiTextareaModule,
	TuiTilesModule,
	TuiToYearPipeModule,
	TuiToggleModule,
	TuiTreeModule,
	TuiUnfinishedValidatorModule,
	TuiUnmaskHandlerModule,
	TuiValueAccessorModule
} from '@taiga-ui/kit';


import {
	TuiArcChartModule,
	TuiAxesModule,
	TuiBarChartModule,
	TuiBarModule,
	TuiBarSetModule,
	TuiLegendItemModule,
	TuiLineChartModule,
	TuiLineDaysChartModule,
	TuiPieChartModule,
	TuiRingChartModule
} from '@taiga-ui/addon-charts';
import {
	TuiCardModule,
	TuiCurrencyPipeModule,
	TuiFormatCardModule,
	TuiInputCVCModule,
	TuiInputCardGroupedModule,
	TuiInputCardModule,
	TuiInputExpireModule,
	TuiMoneyModule,
	TuiThumbnailCardModule
} from '@taiga-ui/addon-commerce';
import {
	TuiAppBarModule,
	TuiDropdownMobileModule,
	TuiElasticStickyModule,
	TuiMobileCalendarDialogModule,
	TuiMobileCalendarModule,
	TuiMobileDialogModule,
	TuiMobileTabsModule,
	TuiPullToRefreshModule,
	TuiRippleModule,
	TuiSheetDialogModule,
	TuiSheetModule,
	TuiSidebarModule,
	TuiTabBarModule,
	TuiThemeAndroidModule,
	TuiThemeIosModule,
	TuiTouchableModule
} from '@taiga-ui/addon-mobile';
// import {
// 	TuiPreviewActionModule,
// 	TuiPreviewDialogModule,
// 	TuiPreviewModule
// } from '@taiga-ui/addon-preview';
// import {
// 	TuiReorderModule,
// 	TuiTableFiltersModule,
// 	TuiTableModule,
// 	TuiTablePaginationModule
// } from '@taiga-ui/addon-table';
import {
	TuiTableBarsHostModule
} from '@taiga-ui/addon-tablebars';
import {  
	
	TuiButtonGroupModule, TuiCellModule, TuiChipModule,  TuiIconModule, TuiSegmentedModule, 
	TuiSkeletonModule} from '@taiga-ui/experimental';

	import {  TuiBlockStatusModule} from '@taiga-ui/layout';

export const TAIGA_MODULES = [
	TuiSegmentedModule,
	TuiChipModule,
	TuiButtonGroupModule,
	TuiIconModule,

	TuiBlockStatusModule,
	TuiSkeletonModule,
	TuiCellModule,
	


	MaskitoModule,
	/* CDK */
	TuiActiveZoneModule,
	TuiAlertHostModule,
	TuiAutoFocusModule,
	TuiAutofilledModule,
	TuiCheckedModule,
	TuiClickOutsideModule,
	TuiControlModule,
	TuiCopyProcessorModule,
	TuiDialogHostModule,
	TuiDragModule,
	TuiDropdownHostModule,
	TuiDroppableModule,
	TuiElementModule,
	TuiFilterPipeModule,
	TuiFocusTrapModule,
	TuiFocusVisibleModule,
	TuiFocusableModule,
	TuiFocusedModule,
	TuiForAsyncModule,
	TuiForModule,
	TuiHighDpiModule,
	TuiHoveredModule,
	TuiIsPresentPipeModule,
	TuiItemModule,
	TuiKeysPipeModule,
	TuiLetModule,
	TuiMapperPipeModule,
	TuiMediaModule,
	TuiObscuredModule,
	TuiOverscrollModule,
	TuiPanModule,
	TuiPlatformModule,
	TuiPortalModule,
	TuiPressedModule,
	TuiPreventDefaultModule,
	TuiRepeatTimesModule,
	TuiReplacePipeModule,
	TuiResizeModule,
	TuiResizerModule,
	TuiScrollControlsModule,
	TuiSwipeModule,
	TuiValidatorModule,
	TuiValueChangesModule,
	TuiZoomModule,
	/* CORE */
	TuiAlertModule,
	TuiButtonModule,
	TuiCalendarModule,
	TuiCalendarSheetPipeModule,
	TuiDataListModule,
	TuiDialogModule,
	TuiDropdownModule,
	TuiErrorModule,
	TuiExpandModule,
	TuiFlagPipeModule,
	TuiFormatDatePipeModule,
	TuiFormatNumberPipeModule,
	TuiFormatPhonePipeModule,
	TuiGroupModule,
	TuiHintModule,
	TuiHintsHostModule,
	TuiHostedDropdownModule,
	TuiLabelModule,
	TuiLinkModule,
	TuiLoaderModule,
	TuiMaskAccessorModule,
	TuiModeModule,
	TuiMonthPipeModule,
	TuiNotificationModule,
	TuiNumberFormatModule,
	TuiPrimitiveCalendarModule,
	TuiPrimitiveCheckboxModule,
	TuiPrimitiveSpinButtonModule,
	TuiPrimitiveTextfieldModule,
	TuiPrimitiveYearMonthPaginationModule,
	TuiPrimitiveYearPickerModule,
	TuiRootModule,
	TuiScrollIntoViewModule,
	TuiScrollbarModule,
	TuiSvgDefsHostModule,
	TuiSvgModule,
	TuiTextfieldControllerModule,
	TuiThemeNightModule,
	TuiTooltipModule,
	TuiWrapperModule,
	/* KIT */
	TextMaskModule,
	TuiAccordionModule,
	TuiActionModule,
	TuiArrowModule,
	TuiAvatarModule,
	TuiBadgeModule,
	TuiBadgedContentModule,
	TuiBreadcrumbsModule,
	TuiCalendarMonthModule,
	TuiCalendarRangeModule,
	TuiCarouselModule,
	TuiCheckboxBlockModule,
	TuiCheckboxLabeledModule,
	TuiCheckboxModule,
	TuiComboBoxModule,
	TuiDataListDropdownManagerModule,
	TuiDataListWrapperModule,
	TuiElasticContainerModule,
	TuiExtractCountryCodeModule,
	TuiFieldErrorPipeModule,
	TuiFilesModule,
	TuiFilterByInputPipeModule,
	TuiFilterModule,
	TuiHighlightModule,
	TuiInputCopyModule,
	TuiInputCountModule,
	TuiInputDateModule,
	TuiInputDateMultiModule,
	TuiInputDateRangeModule,
	TuiInputDateTimeModule,
	TuiInputFilesModule,
	TuiInputInlineModule,
	TuiInputModule,
	TuiInputMonthModule,
	TuiInputMonthRangeModule,
	TuiInputNumberModule,
	TuiInputPasswordModule,
	TuiInputPhoneInternationalModule,
	TuiInputPhoneModule,
	TuiInputRangeModule,
	TuiInputSliderModule,
	TuiInputTagModule,
	TuiInputTimeModule,
	TuiInputYearModule,
	TuiIslandModule,
	TuiIsoToCountryCodeModule,
	TuiItemsWithMoreModule,
	TuiLazyLoadingModule,
	TuiLineClampModule,
	TuiMarkerIconModule,
	TuiMultiSelectModule,
	TuiMultiSelectOptionModule,
	TuiPaginationModule,
	TuiPdfViewerModule,
	TuiPresentModule,
	TuiPrimitiveCalendarRangeModule,
	TuiProgressModule,
	TuiProjectClassModule,
	TuiPromptModule,
	TuiPushModule,
	TuiRadioBlockModule,
	TuiRadioGroupModule,
	TuiRadioLabeledModule,
	TuiRadioListModule,
	TuiRadioModule,
	TuiRangeModule,
	TuiRatingModule,
	TuiRoutableDialogModule,
	TuiSelectModule,
	TuiSelectOptionModule,
	TuiSliderModule,
	TuiSortCountriesPipeModule,
	TuiStepperModule,
	TuiStringifyContentPipeModule,
	TuiStringifyPipeModule,
	TuiTabsModule,
	TuiTagModule,
	TuiTextAreaModule,
	TuiTextareaModule,
	TuiTilesModule,
	TuiToYearPipeModule,
	TuiToggleModule,
	TuiTreeModule,
	TuiUnfinishedValidatorModule,
	TuiUnmaskHandlerModule,
	TuiValueAccessorModule,

	/* ADDON-CHARTS */
	TuiArcChartModule,
	TuiAxesModule,
	TuiBarChartModule,
	TuiBarModule,
	TuiBarSetModule,
	TuiLegendItemModule,
	TuiLineChartModule,
	TuiLineDaysChartModule,
	TuiPieChartModule,
	TuiRingChartModule,
	/* ADDON-COMMERCE */
	TuiCardModule,
	TuiCurrencyPipeModule,
	TuiFormatCardModule,
	TuiInputCVCModule,
	TuiInputCardGroupedModule,
	TuiInputCardModule,
	TuiInputExpireModule,
	TuiMoneyModule,
	TuiThumbnailCardModule,
	/* ADDON-MOBILE */
	TuiAppBarModule,
	TuiDropdownMobileModule,
	TuiElasticStickyModule,
	TuiMobileCalendarDialogModule,
	TuiMobileCalendarModule,
	TuiMobileDialogModule,
	TuiMobileTabsModule,
	TuiPullToRefreshModule,
	TuiRippleModule,
	TuiSheetDialogModule,
	TuiSheetModule,
	TuiSidebarModule,
	TuiTabBarModule,
	TuiThemeAndroidModule,
	TuiThemeIosModule,
	TuiTouchableModule,
	/* ADDON-PREVIEW */
	// TuiPreviewActionModule,
	// TuiPreviewDialogModule,
	// TuiPreviewModule,
	/* ADDON-TABLE */
	// TuiReorderModule,
	// TuiTableFiltersModule,
	// TuiTableModule,
	// TuiTablePaginationModule,
	/* ADDON-TABLEBARS */
	TuiTableBarsHostModule,
	/* EXAMPLE MODULES */
	

];
